version: '3.8'
services: 
    java-springboot:
        build:
            context: .
        ports: 
            - 8000:8000
            - 8080:8080
        environment: 
            - SERVER_PORT=8080
            - MYSQL_URL=jdbc:mysql://mysql-server/mydatabase
        volumes: 
            - ./:/app
        command: ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
    
    mysql-server:
        image: mysql:5.7
        ports: 
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=12345
            - MYSQL_USER=jhonmc
            - MYSQL_PASSWORD=12345
            - MYSQL_DATABASE=mydatabase  